name: 'mydatabricks'
version: '1.0.0'
config-version: 2

profile: 'mydatabricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  use_materialization_v2: True

models:
  mydatabricks:
    +materialized: view
    staging:
      +liquid_clustered_by: ["anonymous_id", "user_id"]
    example:
      +materialized: view
  id_stitching:
    +enabled: false

# --- VARIABLES SECTION (Corrected) ---
vars:
  id_stitching:
    sources:
      - table: pages
        schema: createsco_dev
        user_id_col: id
        anonymous_id_col: anonymous_id
        timestamp_col: timestamp
      
      - table: tracks
        schema: createsco_dev
        user_id_col: id
        anonymous_id_col: anonymous_id
        timestamp_col: timestamp

    target_schema: "rudder_derived"